In [2]:
import sys
print(sys.version)
import numpy as np
print(np.__version__)
import pandas as pd
print(pd.__version__)
import matplotlib.pyplot as plt

%matplotlib inline

3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)]
1.18.1
1.0.1

In [3]:
# Load Original PIRUS File
file = "../og_data/PIRUS_May2020/PIRUS_Public_May2020.xlsx"
pirus = pd.read_excel(file, parse_dates=['Date_Exposure', 'Convert_Date', 'Reawakening_Date'])

In [4]:
# Remove all spaces from column names and convert to lower case
pirus.rename(columns=lambda x: x.replace(' ','_').lower(), inplace=True)

In [5]:
# Set index to subject_id
pirus.set_index(pirus['subject_id'], inplace = True)
pirus.index.name = 'subject_id'

In [6]:
# Drop unnecessary fields: 
unnecessary_fields = ['subject_id', 'age_child', 
                      'itinerant','group_competition', 
                      'current_status', 'changing_target', 
                      'internet_use_plot', 'loc_plot_state2',
                      'loc_plot_city2', 'plot_target2', 'plot_target3',
                      'terrorist_group_name2', 'terrorist_group_name3',
                      'recruiter2', 'recruiter3', 'actively_connect',
                      'media_radicalization', 'social_media_platform2',
                      'social_media_platform3', 'social_media_platform4',
                      'social_media_platform5', 'social_media_activities2',
                      'social_media_activities3', 'social_media_activities4',
                      'social_media_activities5', 'social_media_activities6',
                      'social_media_activities7', 'ideological_sub_category2',
                      'ideological_sub_category3', 'loc_habitation_state2',
                      'loc_habitation_city2', 'rad_duration', 'event_influence2',
                      'event_influence3', 'event_influence4', 'beliefs_trajectory',
                      'behaviors_trajectory', 'radicalization_place', 'religious_background',
                      'reawakening', 'reawakening_date','change_performance',
                      'social_stratum_childhood', 'aspirations', 'abuse_type2',
                      'abuse_type3', 'absent_parent','overseas_family',
                      'close_family', 'family_religiosity','family_ideology',
                      'family_ideological_level', 'prison_family_friend',
                      'crime_family_friend', 'radical_family', 'radical_signif_other',
                      'relationship_troubles', 'platonic_troubles', 'unstructured_time',
                      'friendship_source1', 'friendship_source2', 'friendship_source3',
                      'kicked_out', 'previous_criminal_activity_type2',
                      'previous_criminal_activity_type3', 'trauma', 'standing']
pirus.drop(unnecessary_fields, axis=1, inplace=True)

In [7]:
# Add year and month columns (derived from date_exposure)
pirus['year'] = pd.DatetimeIndex(pirus['date_exposure']).year
pirus['month'] = pd.DatetimeIndex(pirus['date_exposure']).month

In [8]:
# Remove years that are not between 1980 and 2019
mask = (pirus['year'] > 1980) & (pirus['year'] < 2019)
pirus = pirus.loc[mask]

In [9]:
def special_nan_counter(ser, code):
    try:
        return ser.value_counts()[code]
    except:
        return 0

def build_nan_dict(df):
    # Loop through columns to built a column/NaN value dictionary
    d = {}
    for col in df.columns:
        count_nan = df[col].isna().sum()
        count_88 = special_nan_counter(df[col], '-88') + special_nan_counter(df[col], -88)
        count_99 = special_nan_counter(df[col], '-99') + special_nan_counter(df[col], -99)
        #count_sum = count_nan + count_88 + count_99
        count_sum =  count_88 + count_99
        count_normal = df[col].size - count_sum
        typ = df[col].dtype
        
        d.update({col : {'column_name': col, 
                         'type' : typ, 
                         'Normal Value' : count_normal, 
                         'NaN' : count_nan, 
                         '-88' : count_88, 
                         '-99' : count_99, 
                         'sum' : count_sum}})
    return d

def nan_analysis(df):
    '''Convert nan_dict into a dataframe.'''
    df = pd.DataFrame(build_nan_dict(pirus)).T
    df.index = df.column_name
    df.drop('column_name', axis = 1, inplace=True)
    
    mask = df['sum'] == 0
    df = df.loc[~mask]
    
    df.drop('sum', axis=1, inplace=True)
    df.name = 'NaN Value Counts by Column'
    
    print(df.name)
    print(df.type.size, 'rows')
    print(df)
    return df

df = nan_analysis(pirus)

NaN Value Counts by Column
68 rows
                              type Normal Value NaN   -88  -99
column_name
loc_plot_state1             object         1855   0     0   17
loc_plot_city1              object         1644   0     1  227
date_exposure       datetime64[ns]         1870   0     1    1
plot_target1                 int64          916   0   936   20
attack_preparation           int64          796   0   936  140
...                            ...          ...  ..   ...  ...
gang                         int64         1863   0     0    9
gang_age_joined             object            6   0  1846   20
other_ideologies             int64         1864   0     0    8
angry_us                     int64         1136   0     0  736
group_grievance              int64         1087   0     0  785

[68 rows x 5 columns]

In [10]:
# Remove Special NaN Values
for col in pirus.columns:
    pirus[col] = pirus[col].replace(to_replace=[-99,'-99'], value=np.nan)

In [11]:
nan_analysis(pirus)

NaN Value Counts by Column
36 rows
                                            type Normal Value   NaN   -88 -99
column_name
loc_plot_city1                            object         1870   226     1   1
date_exposure                     datetime64[ns]         1870     0     1   1
plot_target1                             float64          936    20   936   0
attack_preparation                       float64          936   140   936   0
op_security                              float64          936   309   936   0
anticp_fatals_targ                       float64          936   216   936   0
criminal_severity                        float64         1871    13     1   0
criminal_charges                         float64         1710    64   162   0
indict_arrest                            float64         1705    23   167   0
terrorist_group_name1                     object         1064    39   808   0
recruiter1                               float64         1130   899   742   0
role_group                               float64         1396   126   476   0
length_group                             float64         1396   928   476   0
clique_radicalize                        float64         1173   779   699   0
clique_connect                           float64         1173   751   699   0
internet_radicalization                  float64         1571   831   301   0
social_media                             float64         1119   468   753   0
social_media_frequency                   float64          869   646  1003   0
social_media_platform1                   float64          869   475  1003   0
social_media_activities1                 float64          869   471  1003   0
loc_habitation_city1                      object         1870   715     1   1
foreign_govt_leader                      float64         1871   797     1   0
event_influence1                         float64         1868   932     4   0
prison_radicalize                        float64          831   688  1041   0
convert_date                              object          310   195  1562   0
immigrant_source                          object          472   152  1400   0
language_english                         float64          355   167  1517   0
diaspora_ties                            float64          547   395  1325   0
education_change                         float64         1069   980   803   0
work_history                             float64         1774  1017    98   0
social_stratum_adulthood                 float64         1842   907    30   0
abuse_adult                                int64         1850     0    22   0
abuse_type1                              float64           79    11  1793   0
previous_criminal_activity_type1         float64         1192   719   680   0
previous_criminal_activity_age           float64         1194   752   678   0
gang_age_joined                          float64           26    20  1846   0

                                            type Normal Value   NaN   -88 -99
column_name
loc_plot_city1                            object         1870   226     1   1
date_exposure                     datetime64[ns]         1870     0     1   1
plot_target1                             float64          936    20   936   0
attack_preparation                       float64          936   140   936   0
op_security                              float64          936   309   936   0
anticp_fatals_targ                       float64          936   216   936   0
criminal_severity                        float64         1871    13     1   0
criminal_charges                         float64         1710    64   162   0
indict_arrest                            float64         1705    23   167   0
terrorist_group_name1                     object         1064    39   808   0
recruiter1                               float64         1130   899   742   0
role_group                               float64         1396   126   476   0
length_group                             float64         1396   928   476   0
clique_radicalize                        float64         1173   779   699   0
clique_connect                           float64         1173   751   699   0
internet_radicalization                  float64         1571   831   301   0
social_media                             float64         1119   468   753   0
social_media_frequency                   float64          869   646  1003   0
social_media_platform1                   float64          869   475  1003   0
social_media_activities1                 float64          869   471  1003   0
loc_habitation_city1                      object         1870   715     1   1
foreign_govt_leader                      float64         1871   797     1   0
event_influence1                         float64         1868   932     4   0
prison_radicalize                        float64          831   688  1041   0
convert_date                              object          310   195  1562   0
immigrant_source                          object          472   152  1400   0
language_english                         float64          355   167  1517   0
diaspora_ties                            float64          547   395  1325   0
education_change                         float64         1069   980   803   0
work_history                             float64         1774  1017    98   0
social_stratum_adulthood                 float64         1842   907    30   0
abuse_adult                                int64         1850     0    22   0
abuse_type1                              float64           79    11  1793   0
previous_criminal_activity_type1         float64         1192   719   680   0
previous_criminal_activity_age           float64         1194   752   678   0
gang_age_joined                          float64           26    20  1846   0

In [12]:
# Save Data to CSV
pirus.to_csv('../clean_data/pirus_deep_clean_4121.csv')